---
ID: "2c5ebb3c-c9ee-45cd-91fb-7f4966edbc73"
Parent: "222b4bad-693b-4b6e-9cac-d2ae55629b2b"
Template: "222b4bad-693b-4b6e-9cac-d2ae55629b2b"
Path: /sitecore/templates/Feature/About/TeamIcon/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180821T172319Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
