---
ID: "852b3da2-4854-4b86-bf93-08b8ecd11691"
Parent: "9b2b18cc-7417-41b0-9c1e-514272c669ee"
Template: "9b2b18cc-7417-41b0-9c1e-514272c669ee"
Path: /sitecore/templates/Feature/About/Clients/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <p
          key="content"
          uid="{CC77F0D2-F90B-4625-9342-A17FE9D08DDB}"
          md="{FB02E098-5C21-445D-808F-A2025D0402A1}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180807T192937Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
