---
ID: "036cc99f-4d9f-4bec-8bb3-97bbe1b1cc36"
Parent: "3fcf8127-d125-40c5-8b76-56ed63aa3219"
Template: "3fcf8127-d125-40c5-8b76-56ed63aa3219"
Path: /sitecore/templates/Feature/Services/PortifolioItem/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180802T173114Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "eeb13e14-a768-4bad-97a8-5f50693e32e3"
      Hint: Subtitle
      Value: $name
    - ID: "f14eca0b-7f7d-4d06-9dbb-3e9441b4a1dd"
      Hint: Title
      Value: $name
