---
ID: "b5f4808c-a6ec-4755-858b-74be5547fe6d"
Parent: "8585147a-1260-45de-bd4c-b09592e0748a"
Template: "8585147a-1260-45de-bd4c-b09592e0748a"
Path: /sitecore/templates/Feature/Media/Page Footer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180807T005733Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7be60e65-fdee-4da9-99af-6ec2a243abaf"
      Hint: Twitter
      Value: |
        <link text="Twitter" linktype="external" url="https://twitter.com/" anchor="" target="" />
    - ID: "804ff10c-d961-4624-8433-60716bd5c505"
      Hint: Linkedin
      Value: |
        <link text="Linkedin" linktype="external" url="https://br.linkedin.com/" anchor="" target="" />
    - ID: "82ee80ad-d44e-4bac-8d5f-8de02be18dcb"
      Hint: Facebook
      Value: |
        <link text="Facebook" linktype="external" url="http://facebook.com" anchor="" target="" />
    - ID: "9c9273ec-0ec0-468f-924f-207ea42468aa"
      Hint: Copyright
      Value: Copyright © Your Website 2018
